// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	repository "golang-order-manager-api/internal/repositories"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderTx is an autogenerated mock type for the OrderTx type
type MockOrderTx struct {
	mock.Mock
}

type MockOrderTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderTx) EXPECT() *MockOrderTx_Expecter {
	return &MockOrderTx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with no fields
func (_m *MockOrderTx) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockOrderTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockOrderTx_Expecter) Commit() *MockOrderTx_Commit_Call {
	return &MockOrderTx_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockOrderTx_Commit_Call) Run(run func()) *MockOrderTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderTx_Commit_Call) Return(_a0 error) *MockOrderTx_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderTx_Commit_Call) RunAndReturn(run func() error) *MockOrderTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// OrderRepository provides a mock function with no fields
func (_m *MockOrderTx) OrderRepository() repository.OrderRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OrderRepository")
	}

	var r0 repository.OrderRepository
	if rf, ok := ret.Get(0).(func() repository.OrderRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.OrderRepository)
		}
	}

	return r0
}

// MockOrderTx_OrderRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderRepository'
type MockOrderTx_OrderRepository_Call struct {
	*mock.Call
}

// OrderRepository is a helper method to define mock.On call
func (_e *MockOrderTx_Expecter) OrderRepository() *MockOrderTx_OrderRepository_Call {
	return &MockOrderTx_OrderRepository_Call{Call: _e.mock.On("OrderRepository")}
}

func (_c *MockOrderTx_OrderRepository_Call) Run(run func()) *MockOrderTx_OrderRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderTx_OrderRepository_Call) Return(_a0 repository.OrderRepository) *MockOrderTx_OrderRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderTx_OrderRepository_Call) RunAndReturn(run func() repository.OrderRepository) *MockOrderTx_OrderRepository_Call {
	_c.Call.Return(run)
	return _c
}

// ProductRepository provides a mock function with no fields
func (_m *MockOrderTx) ProductRepository() repository.ProductRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProductRepository")
	}

	var r0 repository.ProductRepository
	if rf, ok := ret.Get(0).(func() repository.ProductRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ProductRepository)
		}
	}

	return r0
}

// MockOrderTx_ProductRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProductRepository'
type MockOrderTx_ProductRepository_Call struct {
	*mock.Call
}

// ProductRepository is a helper method to define mock.On call
func (_e *MockOrderTx_Expecter) ProductRepository() *MockOrderTx_ProductRepository_Call {
	return &MockOrderTx_ProductRepository_Call{Call: _e.mock.On("ProductRepository")}
}

func (_c *MockOrderTx_ProductRepository_Call) Run(run func()) *MockOrderTx_ProductRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderTx_ProductRepository_Call) Return(_a0 repository.ProductRepository) *MockOrderTx_ProductRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderTx_ProductRepository_Call) RunAndReturn(run func() repository.ProductRepository) *MockOrderTx_ProductRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with no fields
func (_m *MockOrderTx) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockOrderTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *MockOrderTx_Expecter) Rollback() *MockOrderTx_Rollback_Call {
	return &MockOrderTx_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *MockOrderTx_Rollback_Call) Run(run func()) *MockOrderTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderTx_Rollback_Call) Return(_a0 error) *MockOrderTx_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderTx_Rollback_Call) RunAndReturn(run func() error) *MockOrderTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderTx creates a new instance of MockOrderTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderTx {
	mock := &MockOrderTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
