// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "golang-order-manager-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOrderCache is an autogenerated mock type for the OrderCache type
type MockOrderCache struct {
	mock.Mock
}

type MockOrderCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderCache) EXPECT() *MockOrderCache_Expecter {
	return &MockOrderCache_Expecter{mock: &_m.Mock}
}

// DeleteOrder provides a mock function with given fields: ctx, id
func (_m *MockOrderCache) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderCache_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type MockOrderCache_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderCache_Expecter) DeleteOrder(ctx interface{}, id interface{}) *MockOrderCache_DeleteOrder_Call {
	return &MockOrderCache_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, id)}
}

func (_c *MockOrderCache_DeleteOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderCache_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderCache_DeleteOrder_Call) Return(_a0 error) *MockOrderCache_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderCache_DeleteOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockOrderCache_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *MockOrderCache) GetOrder(ctx context.Context, id uuid.UUID) (models.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderCache_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderCache_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderCache_Expecter) GetOrder(ctx interface{}, id interface{}) *MockOrderCache_GetOrder_Call {
	return &MockOrderCache_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockOrderCache_GetOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderCache_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderCache_GetOrder_Call) Return(_a0 models.Order, _a1 error) *MockOrderCache_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderCache_GetOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.Order, error)) *MockOrderCache_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SetOrder provides a mock function with given fields: ctx, order
func (_m *MockOrderCache) SetOrder(ctx context.Context, order models.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SetOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderCache_SetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrder'
type MockOrderCache_SetOrder_Call struct {
	*mock.Call
}

// SetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order models.Order
func (_e *MockOrderCache_Expecter) SetOrder(ctx interface{}, order interface{}) *MockOrderCache_SetOrder_Call {
	return &MockOrderCache_SetOrder_Call{Call: _e.mock.On("SetOrder", ctx, order)}
}

func (_c *MockOrderCache_SetOrder_Call) Run(run func(ctx context.Context, order models.Order)) *MockOrderCache_SetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Order))
	})
	return _c
}

func (_c *MockOrderCache_SetOrder_Call) Return(_a0 error) *MockOrderCache_SetOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderCache_SetOrder_Call) RunAndReturn(run func(context.Context, models.Order) error) *MockOrderCache_SetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderCache creates a new instance of MockOrderCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderCache {
	mock := &MockOrderCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
