// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	repository "golang-order-manager-api/internal/repositories"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderTxFactory is an autogenerated mock type for the OrderTxFactory type
type MockOrderTxFactory struct {
	mock.Mock
}

type MockOrderTxFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderTxFactory) EXPECT() *MockOrderTxFactory_Expecter {
	return &MockOrderTxFactory_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockOrderTxFactory) BeginTx(ctx context.Context) (repository.OrderTx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.OrderTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.OrderTx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.OrderTx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.OrderTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderTxFactory_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockOrderTxFactory_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderTxFactory_Expecter) BeginTx(ctx interface{}) *MockOrderTxFactory_BeginTx_Call {
	return &MockOrderTxFactory_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockOrderTxFactory_BeginTx_Call) Run(run func(ctx context.Context)) *MockOrderTxFactory_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOrderTxFactory_BeginTx_Call) Return(_a0 repository.OrderTx, _a1 error) *MockOrderTxFactory_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderTxFactory_BeginTx_Call) RunAndReturn(run func(context.Context) (repository.OrderTx, error)) *MockOrderTxFactory_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderTxFactory creates a new instance of MockOrderTxFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderTxFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderTxFactory {
	mock := &MockOrderTxFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
