// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "golang-order-manager-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: o
func (_m *MockOrderRepository) Create(o models.Order) (models.Order, error) {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Order) (models.Order, error)); ok {
		return rf(o)
	}
	if rf, ok := ret.Get(0).(func(models.Order) models.Order); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(models.Order) error); ok {
		r1 = rf(o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - o models.Order
func (_e *MockOrderRepository_Expecter) Create(o interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", o)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(o models.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Order))
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(_a0 models.Order, _a1 error) *MockOrderRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(models.Order) (models.Order, error)) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItems provides a mock function with given fields: orderID, items
func (_m *MockOrderRepository) CreateItems(orderID uuid.UUID, items []models.OrderItem) ([]models.OrderItem, error) {
	ret := _m.Called(orderID, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateItems")
	}

	var r0 []models.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, []models.OrderItem) ([]models.OrderItem, error)); ok {
		return rf(orderID, items)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, []models.OrderItem) []models.OrderItem); ok {
		r0 = rf(orderID, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, []models.OrderItem) error); ok {
		r1 = rf(orderID, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_CreateItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItems'
type MockOrderRepository_CreateItems_Call struct {
	*mock.Call
}

// CreateItems is a helper method to define mock.On call
//   - orderID uuid.UUID
//   - items []models.OrderItem
func (_e *MockOrderRepository_Expecter) CreateItems(orderID interface{}, items interface{}) *MockOrderRepository_CreateItems_Call {
	return &MockOrderRepository_CreateItems_Call{Call: _e.mock.On("CreateItems", orderID, items)}
}

func (_c *MockOrderRepository_CreateItems_Call) Run(run func(orderID uuid.UUID, items []models.OrderItem)) *MockOrderRepository_CreateItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].([]models.OrderItem))
	})
	return _c
}

func (_c *MockOrderRepository_CreateItems_Call) Return(_a0 []models.OrderItem, _a1 error) *MockOrderRepository_CreateItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_CreateItems_Call) RunAndReturn(run func(uuid.UUID, []models.OrderItem) ([]models.OrderItem, error)) *MockOrderRepository_CreateItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function with given fields: userID, limit, offset, f
func (_m *MockOrderRepository) GetAllByUserID(userID uuid.UUID, limit int, offset int, f models.OrderFilter) ([]models.Order, int, error) {
	ret := _m.Called(userID, limit, offset, f)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []models.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, models.OrderFilter) ([]models.Order, int, error)); ok {
		return rf(userID, limit, offset, f)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, models.OrderFilter) []models.Order); ok {
		r0 = rf(userID, limit, offset, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int, models.OrderFilter) int); ok {
		r1 = rf(userID, limit, offset, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int, models.OrderFilter) error); ok {
		r2 = rf(userID, limit, offset, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderRepository_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockOrderRepository_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - userID uuid.UUID
//   - limit int
//   - offset int
//   - f models.OrderFilter
func (_e *MockOrderRepository_Expecter) GetAllByUserID(userID interface{}, limit interface{}, offset interface{}, f interface{}) *MockOrderRepository_GetAllByUserID_Call {
	return &MockOrderRepository_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", userID, limit, offset, f)}
}

func (_c *MockOrderRepository_GetAllByUserID_Call) Run(run func(userID uuid.UUID, limit int, offset int, f models.OrderFilter)) *MockOrderRepository_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int), args[3].(models.OrderFilter))
	})
	return _c
}

func (_c *MockOrderRepository_GetAllByUserID_Call) Return(_a0 []models.Order, _a1 int, _a2 error) *MockOrderRepository_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOrderRepository_GetAllByUserID_Call) RunAndReturn(run func(uuid.UUID, int, int, models.OrderFilter) ([]models.Order, int, error)) *MockOrderRepository_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: orderID
func (_m *MockOrderRepository) GetByID(orderID uuid.UUID) (models.Order, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (models.Order, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) models.Order); ok {
		r0 = rf(orderID)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - orderID uuid.UUID
func (_e *MockOrderRepository_Expecter) GetByID(orderID interface{}) *MockOrderRepository_GetByID_Call {
	return &MockOrderRepository_GetByID_Call{Call: _e.mock.On("GetByID", orderID)}
}

func (_c *MockOrderRepository_GetByID_Call) Run(run func(orderID uuid.UUID)) *MockOrderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) Return(_a0 models.Order, _a1 error) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) RunAndReturn(run func(uuid.UUID) (models.Order, error)) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: orderID, status
func (_m *MockOrderRepository) UpdateStatus(orderID uuid.UUID, status models.OrderStatus) error {
	ret := _m.Called(orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, models.OrderStatus) error); ok {
		r0 = rf(orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - orderID uuid.UUID
//   - status models.OrderStatus
func (_e *MockOrderRepository_Expecter) UpdateStatus(orderID interface{}, status interface{}) *MockOrderRepository_UpdateStatus_Call {
	return &MockOrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", orderID, status)}
}

func (_c *MockOrderRepository_UpdateStatus_Call) Run(run func(orderID uuid.UUID, status models.OrderStatus)) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(models.OrderStatus))
	})
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) Return(_a0 error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) RunAndReturn(run func(uuid.UUID, models.OrderStatus) error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
