// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "golang-order-manager-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	repository "golang-order-manager-api/internal/repositories"

	uuid "github.com/google/uuid"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: p
func (_m *MockProductRepository) Create(p models.Product) (models.Product, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Product) (models.Product, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(models.Product) models.Product); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(models.Product) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - p models.Product
func (_e *MockProductRepository_Expecter) Create(p interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", p)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(p models.Product)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Product))
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(_a0 models.Product, _a1 error) *MockProductRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(models.Product) (models.Product, error)) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementStock provides a mock function with given fields: productID, quantity
func (_m *MockProductRepository) DecrementStock(productID uuid.UUID, quantity int) error {
	ret := _m.Called(productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DecrementStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) error); ok {
		r0 = rf(productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_DecrementStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementStock'
type MockProductRepository_DecrementStock_Call struct {
	*mock.Call
}

// DecrementStock is a helper method to define mock.On call
//   - productID uuid.UUID
//   - quantity int
func (_e *MockProductRepository_Expecter) DecrementStock(productID interface{}, quantity interface{}) *MockProductRepository_DecrementStock_Call {
	return &MockProductRepository_DecrementStock_Call{Call: _e.mock.On("DecrementStock", productID, quantity)}
}

func (_c *MockProductRepository_DecrementStock_Call) Run(run func(productID uuid.UUID, quantity int)) *MockProductRepository_DecrementStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int))
	})
	return _c
}

func (_c *MockProductRepository_DecrementStock_Call) Return(_a0 error) *MockProductRepository_DecrementStock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_DecrementStock_Call) RunAndReturn(run func(uuid.UUID, int) error) *MockProductRepository_DecrementStock_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockProductRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) Delete(id interface{}) *MockProductRepository_Delete_Call {
	return &MockProductRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockProductRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_Delete_Call) Return(_a0 error) *MockProductRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: limit, offset, f
func (_m *MockProductRepository) GetAll(limit int, offset int, f repository.ProductFilter) ([]models.Product, int, error) {
	ret := _m.Called(limit, offset, f)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Product
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, repository.ProductFilter) ([]models.Product, int, error)); ok {
		return rf(limit, offset, f)
	}
	if rf, ok := ret.Get(0).(func(int, int, repository.ProductFilter) []models.Product); ok {
		r0 = rf(limit, offset, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, repository.ProductFilter) int); ok {
		r1 = rf(limit, offset, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int, repository.ProductFilter) error); ok {
		r2 = rf(limit, offset, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProductRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockProductRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - limit int
//   - offset int
//   - f repository.ProductFilter
func (_e *MockProductRepository_Expecter) GetAll(limit interface{}, offset interface{}, f interface{}) *MockProductRepository_GetAll_Call {
	return &MockProductRepository_GetAll_Call{Call: _e.mock.On("GetAll", limit, offset, f)}
}

func (_c *MockProductRepository_GetAll_Call) Run(run func(limit int, offset int, f repository.ProductFilter)) *MockProductRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(repository.ProductFilter))
	})
	return _c
}

func (_c *MockProductRepository_GetAll_Call) Return(_a0 []models.Product, _a1 int, _a2 error) *MockProductRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProductRepository_GetAll_Call) RunAndReturn(run func(int, int, repository.ProductFilter) ([]models.Product, int, error)) *MockProductRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockProductRepository) GetByID(id uuid.UUID) (models.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (models.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) models.Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProductRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) GetByID(id interface{}) *MockProductRepository_GetByID_Call {
	return &MockProductRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockProductRepository_GetByID_Call) Run(run func(id uuid.UUID)) *MockProductRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_GetByID_Call) Return(_a0 models.Product, _a1 error) *MockProductRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_GetByID_Call) RunAndReturn(run func(uuid.UUID) (models.Product, error)) *MockProductRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementStock provides a mock function with given fields: productID, quantity
func (_m *MockProductRepository) IncrementStock(productID uuid.UUID, quantity int) error {
	ret := _m.Called(productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for IncrementStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) error); ok {
		r0 = rf(productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_IncrementStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementStock'
type MockProductRepository_IncrementStock_Call struct {
	*mock.Call
}

// IncrementStock is a helper method to define mock.On call
//   - productID uuid.UUID
//   - quantity int
func (_e *MockProductRepository_Expecter) IncrementStock(productID interface{}, quantity interface{}) *MockProductRepository_IncrementStock_Call {
	return &MockProductRepository_IncrementStock_Call{Call: _e.mock.On("IncrementStock", productID, quantity)}
}

func (_c *MockProductRepository_IncrementStock_Call) Run(run func(productID uuid.UUID, quantity int)) *MockProductRepository_IncrementStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int))
	})
	return _c
}

func (_c *MockProductRepository_IncrementStock_Call) Return(_a0 error) *MockProductRepository_IncrementStock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_IncrementStock_Call) RunAndReturn(run func(uuid.UUID, int) error) *MockProductRepository_IncrementStock_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, name, description, price, stock
func (_m *MockProductRepository) Update(id uuid.UUID, name string, description string, price *float64, stock *int) (models.Product, error) {
	ret := _m.Called(id, name, description, price, stock)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, *float64, *int) (models.Product, error)); ok {
		return rf(id, name, description, price, stock)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, *float64, *int) models.Product); ok {
		r0 = rf(id, name, description, price, stock)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, string, *float64, *int) error); ok {
		r1 = rf(id, name, description, price, stock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uuid.UUID
//   - name string
//   - description string
//   - price *float64
//   - stock *int
func (_e *MockProductRepository_Expecter) Update(id interface{}, name interface{}, description interface{}, price interface{}, stock interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", id, name, description, price, stock)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(id uuid.UUID, name string, description string, price *float64, stock *int)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(string), args[3].(*float64), args[4].(*int))
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(_a0 models.Product, _a1 error) *MockProductRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(uuid.UUID, string, string, *float64, *int) (models.Product, error)) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
