// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "golang-order-manager-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: user
func (_m *MockUserRepository) CreateUser(user models.User) (models.User, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(models.User) (models.User, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(models.User) models.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(models.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user models.User
func (_e *MockUserRepository_Expecter) CreateUser(user interface{}) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(user models.User)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.User))
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(_a0 models.User, _a1 error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(models.User) (models.User, error)) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByID provides a mock function with given fields: id
func (_m *MockUserRepository) DeleteUserByID(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_DeleteUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByID'
type MockUserRepository_DeleteUserByID_Call struct {
	*mock.Call
}

// DeleteUserByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) DeleteUserByID(id interface{}) *MockUserRepository_DeleteUserByID_Call {
	return &MockUserRepository_DeleteUserByID_Call{Call: _e.mock.On("DeleteUserByID", id)}
}

func (_c *MockUserRepository_DeleteUserByID_Call) Run(run func(id uuid.UUID)) *MockUserRepository_DeleteUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_DeleteUserByID_Call) Return(err error) *MockUserRepository_DeleteUserByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_DeleteUserByID_Call) RunAndReturn(run func(uuid.UUID) error) *MockUserRepository_DeleteUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: email
func (_m *MockUserRepository) GetByEmail(email string) (models.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(email interface{}) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(user models.User, err error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(string) (models.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockUserRepository) GetByID(id uuid.UUID) (models.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (models.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) models.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) GetByID(id interface{}) *MockUserRepository_GetByID_Call {
	return &MockUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockUserRepository_GetByID_Call) Run(run func(id uuid.UUID)) *MockUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_GetByID_Call) Return(user models.User, err error) *MockUserRepository_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByID_Call) RunAndReturn(run func(uuid.UUID) (models.User, error)) *MockUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// IsEmailAlreadyInUse provides a mock function with given fields: email, excludedID
func (_m *MockUserRepository) IsEmailAlreadyInUse(email string, excludedID *uuid.UUID) (bool, error) {
	ret := _m.Called(email, excludedID)

	if len(ret) == 0 {
		panic("no return value specified for IsEmailAlreadyInUse")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *uuid.UUID) (bool, error)); ok {
		return rf(email, excludedID)
	}
	if rf, ok := ret.Get(0).(func(string, *uuid.UUID) bool); ok {
		r0 = rf(email, excludedID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *uuid.UUID) error); ok {
		r1 = rf(email, excludedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_IsEmailAlreadyInUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmailAlreadyInUse'
type MockUserRepository_IsEmailAlreadyInUse_Call struct {
	*mock.Call
}

// IsEmailAlreadyInUse is a helper method to define mock.On call
//   - email string
//   - excludedID *uuid.UUID
func (_e *MockUserRepository_Expecter) IsEmailAlreadyInUse(email interface{}, excludedID interface{}) *MockUserRepository_IsEmailAlreadyInUse_Call {
	return &MockUserRepository_IsEmailAlreadyInUse_Call{Call: _e.mock.On("IsEmailAlreadyInUse", email, excludedID)}
}

func (_c *MockUserRepository_IsEmailAlreadyInUse_Call) Run(run func(email string, excludedID *uuid.UUID)) *MockUserRepository_IsEmailAlreadyInUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_IsEmailAlreadyInUse_Call) Return(exists bool, err error) *MockUserRepository_IsEmailAlreadyInUse_Call {
	_c.Call.Return(exists, err)
	return _c
}

func (_c *MockUserRepository_IsEmailAlreadyInUse_Call) RunAndReturn(run func(string, *uuid.UUID) (bool, error)) *MockUserRepository_IsEmailAlreadyInUse_Call {
	_c.Call.Return(run)
	return _c
}

// IsUsernameAlreadyInUse provides a mock function with given fields: username, excludedID
func (_m *MockUserRepository) IsUsernameAlreadyInUse(username string, excludedID *uuid.UUID) (bool, error) {
	ret := _m.Called(username, excludedID)

	if len(ret) == 0 {
		panic("no return value specified for IsUsernameAlreadyInUse")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *uuid.UUID) (bool, error)); ok {
		return rf(username, excludedID)
	}
	if rf, ok := ret.Get(0).(func(string, *uuid.UUID) bool); ok {
		r0 = rf(username, excludedID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *uuid.UUID) error); ok {
		r1 = rf(username, excludedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_IsUsernameAlreadyInUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUsernameAlreadyInUse'
type MockUserRepository_IsUsernameAlreadyInUse_Call struct {
	*mock.Call
}

// IsUsernameAlreadyInUse is a helper method to define mock.On call
//   - username string
//   - excludedID *uuid.UUID
func (_e *MockUserRepository_Expecter) IsUsernameAlreadyInUse(username interface{}, excludedID interface{}) *MockUserRepository_IsUsernameAlreadyInUse_Call {
	return &MockUserRepository_IsUsernameAlreadyInUse_Call{Call: _e.mock.On("IsUsernameAlreadyInUse", username, excludedID)}
}

func (_c *MockUserRepository_IsUsernameAlreadyInUse_Call) Run(run func(username string, excludedID *uuid.UUID)) *MockUserRepository_IsUsernameAlreadyInUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_IsUsernameAlreadyInUse_Call) Return(exists bool, err error) *MockUserRepository_IsUsernameAlreadyInUse_Call {
	_c.Call.Return(exists, err)
	return _c
}

func (_c *MockUserRepository_IsUsernameAlreadyInUse_Call) RunAndReturn(run func(string, *uuid.UUID) (bool, error)) *MockUserRepository_IsUsernameAlreadyInUse_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: user
func (_m *MockUserRepository) UpdateUser(user models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - user models.User
func (_e *MockUserRepository_Expecter) UpdateUser(user interface{}) *MockUserRepository_UpdateUser_Call {
	return &MockUserRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", user)}
}

func (_c *MockUserRepository_UpdateUser_Call) Run(run func(user models.User)) *MockUserRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.User))
	})
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) Return(err error) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) RunAndReturn(run func(models.User) error) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
