// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// GetRefreshToken provides a mock function with given fields: refreshToken
func (_m *MockAuthRepository) GetRefreshToken(refreshToken string) (uuid.UUID, time.Time, time.Time, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 uuid.UUID
	var r1 time.Time
	var r2 time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, time.Time, time.Time, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) time.Time); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(string) time.Time); ok {
		r2 = rf(refreshToken)
	} else {
		r2 = ret.Get(2).(time.Time)
	}

	if rf, ok := ret.Get(3).(func(string) error); ok {
		r3 = rf(refreshToken)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAuthRepository_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockAuthRepository_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - refreshToken string
func (_e *MockAuthRepository_Expecter) GetRefreshToken(refreshToken interface{}) *MockAuthRepository_GetRefreshToken_Call {
	return &MockAuthRepository_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", refreshToken)}
}

func (_c *MockAuthRepository_GetRefreshToken_Call) Run(run func(refreshToken string)) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthRepository_GetRefreshToken_Call) Return(_a0 uuid.UUID, _a1 time.Time, _a2 time.Time, _a3 error) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAuthRepository_GetRefreshToken_Call) RunAndReturn(run func(string) (uuid.UUID, time.Time, time.Time, error)) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllRefreshTokens provides a mock function with given fields: userID
func (_m *MockAuthRepository) RevokeAllRefreshTokens(userID uuid.UUID) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_RevokeAllRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllRefreshTokens'
type MockAuthRepository_RevokeAllRefreshTokens_Call struct {
	*mock.Call
}

// RevokeAllRefreshTokens is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockAuthRepository_Expecter) RevokeAllRefreshTokens(userID interface{}) *MockAuthRepository_RevokeAllRefreshTokens_Call {
	return &MockAuthRepository_RevokeAllRefreshTokens_Call{Call: _e.mock.On("RevokeAllRefreshTokens", userID)}
}

func (_c *MockAuthRepository_RevokeAllRefreshTokens_Call) Run(run func(userID uuid.UUID)) *MockAuthRepository_RevokeAllRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthRepository_RevokeAllRefreshTokens_Call) Return(_a0 error) *MockAuthRepository_RevokeAllRefreshTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_RevokeAllRefreshTokens_Call) RunAndReturn(run func(uuid.UUID) error) *MockAuthRepository_RevokeAllRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: refreshToken
func (_m *MockAuthRepository) RevokeRefreshToken(refreshToken string) error {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockAuthRepository_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - refreshToken string
func (_e *MockAuthRepository_Expecter) RevokeRefreshToken(refreshToken interface{}) *MockAuthRepository_RevokeRefreshToken_Call {
	return &MockAuthRepository_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", refreshToken)}
}

func (_c *MockAuthRepository_RevokeRefreshToken_Call) Run(run func(refreshToken string)) *MockAuthRepository_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthRepository_RevokeRefreshToken_Call) Return(_a0 error) *MockAuthRepository_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_RevokeRefreshToken_Call) RunAndReturn(run func(string) error) *MockAuthRepository_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function with given fields: userID, refreshToken, expiresAt
func (_m *MockAuthRepository) SaveRefreshToken(userID uuid.UUID, refreshToken string, expiresAt time.Time) error {
	ret := _m.Called(userID, refreshToken, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, time.Time) error); ok {
		r0 = rf(userID, refreshToken, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type MockAuthRepository_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - userID uuid.UUID
//   - refreshToken string
//   - expiresAt time.Time
func (_e *MockAuthRepository_Expecter) SaveRefreshToken(userID interface{}, refreshToken interface{}, expiresAt interface{}) *MockAuthRepository_SaveRefreshToken_Call {
	return &MockAuthRepository_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", userID, refreshToken, expiresAt)}
}

func (_c *MockAuthRepository_SaveRefreshToken_Call) Run(run func(userID uuid.UUID, refreshToken string, expiresAt time.Time)) *MockAuthRepository_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockAuthRepository_SaveRefreshToken_Call) Return(_a0 error) *MockAuthRepository_SaveRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_SaveRefreshToken_Call) RunAndReturn(run func(uuid.UUID, string, time.Time) error) *MockAuthRepository_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
