// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "golang-order-manager-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	repository "golang-order-manager-api/internal/repositories"

	uuid "github.com/google/uuid"
)

// MockProductService is an autogenerated mock type for the ProductService type
type MockProductService struct {
	mock.Mock
}

type MockProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductService) EXPECT() *MockProductService_Expecter {
	return &MockProductService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: p
func (_m *MockProductService) Create(p models.Product) (models.Product, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Product) (models.Product, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(models.Product) models.Product); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(models.Product) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - p models.Product
func (_e *MockProductService_Expecter) Create(p interface{}) *MockProductService_Create_Call {
	return &MockProductService_Create_Call{Call: _e.mock.On("Create", p)}
}

func (_c *MockProductService_Create_Call) Run(run func(p models.Product)) *MockProductService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Product))
	})
	return _c
}

func (_c *MockProductService_Create_Call) Return(_a0 models.Product, _a1 error) *MockProductService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductService_Create_Call) RunAndReturn(run func(models.Product) (models.Product, error)) *MockProductService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockProductService) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductService_Expecter) Delete(id interface{}) *MockProductService_Delete_Call {
	return &MockProductService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockProductService_Delete_Call) Run(run func(id uuid.UUID)) *MockProductService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductService_Delete_Call) Return(_a0 error) *MockProductService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductService_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockProductService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: page, limit, filter
func (_m *MockProductService) GetAll(page int, limit int, filter repository.ProductFilter) ([]models.Product, int, error) {
	ret := _m.Called(page, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Product
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, repository.ProductFilter) ([]models.Product, int, error)); ok {
		return rf(page, limit, filter)
	}
	if rf, ok := ret.Get(0).(func(int, int, repository.ProductFilter) []models.Product); ok {
		r0 = rf(page, limit, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, repository.ProductFilter) int); ok {
		r1 = rf(page, limit, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int, repository.ProductFilter) error); ok {
		r2 = rf(page, limit, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProductService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockProductService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - page int
//   - limit int
//   - filter repository.ProductFilter
func (_e *MockProductService_Expecter) GetAll(page interface{}, limit interface{}, filter interface{}) *MockProductService_GetAll_Call {
	return &MockProductService_GetAll_Call{Call: _e.mock.On("GetAll", page, limit, filter)}
}

func (_c *MockProductService_GetAll_Call) Run(run func(page int, limit int, filter repository.ProductFilter)) *MockProductService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(repository.ProductFilter))
	})
	return _c
}

func (_c *MockProductService_GetAll_Call) Return(_a0 []models.Product, _a1 int, _a2 error) *MockProductService_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProductService_GetAll_Call) RunAndReturn(run func(int, int, repository.ProductFilter) ([]models.Product, int, error)) *MockProductService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockProductService) GetByID(id uuid.UUID) (models.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (models.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) models.Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProductService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductService_Expecter) GetByID(id interface{}) *MockProductService_GetByID_Call {
	return &MockProductService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockProductService_GetByID_Call) Run(run func(id uuid.UUID)) *MockProductService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductService_GetByID_Call) Return(_a0 models.Product, _a1 error) *MockProductService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductService_GetByID_Call) RunAndReturn(run func(uuid.UUID) (models.Product, error)) *MockProductService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, name, description, price, stock
func (_m *MockProductService) Update(id uuid.UUID, name string, description string, price *float64, stock *int) (models.Product, error) {
	ret := _m.Called(id, name, description, price, stock)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, *float64, *int) (models.Product, error)); ok {
		return rf(id, name, description, price, stock)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, *float64, *int) models.Product); ok {
		r0 = rf(id, name, description, price, stock)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, string, *float64, *int) error); ok {
		r1 = rf(id, name, description, price, stock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uuid.UUID
//   - name string
//   - description string
//   - price *float64
//   - stock *int
func (_e *MockProductService_Expecter) Update(id interface{}, name interface{}, description interface{}, price interface{}, stock interface{}) *MockProductService_Update_Call {
	return &MockProductService_Update_Call{Call: _e.mock.On("Update", id, name, description, price, stock)}
}

func (_c *MockProductService_Update_Call) Run(run func(id uuid.UUID, name string, description string, price *float64, stock *int)) *MockProductService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(string), args[3].(*float64), args[4].(*int))
	})
	return _c
}

func (_c *MockProductService_Update_Call) Return(_a0 models.Product, _a1 error) *MockProductService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductService_Update_Call) RunAndReturn(run func(uuid.UUID, string, string, *float64, *int) (models.Product, error)) *MockProductService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductService creates a new instance of MockProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductService {
	mock := &MockProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
