// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "golang-order-manager-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	services "golang-order-manager-api/internal/services"

	uuid "github.com/google/uuid"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: userID, inputs
func (_m *MockOrderService) CreateOrder(userID uuid.UUID, inputs []services.OrderItemInput) (models.Order, error) {
	ret := _m.Called(userID, inputs)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, []services.OrderItemInput) (models.Order, error)); ok {
		return rf(userID, inputs)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, []services.OrderItemInput) models.Order); ok {
		r0 = rf(userID, inputs)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, []services.OrderItemInput) error); ok {
		r1 = rf(userID, inputs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - userID uuid.UUID
//   - inputs []services.OrderItemInput
func (_e *MockOrderService_Expecter) CreateOrder(userID interface{}, inputs interface{}) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", userID, inputs)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(userID uuid.UUID, inputs []services.OrderItemInput)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].([]services.OrderItemInput))
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(_a0 models.Order, _a1 error) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(uuid.UUID, []services.OrderItemInput) (models.Order, error)) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function with given fields: userID, page, limit, filter
func (_m *MockOrderService) GetAllByUserID(userID uuid.UUID, page int, limit int, filter models.OrderFilter) ([]models.Order, int, error) {
	ret := _m.Called(userID, page, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []models.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, models.OrderFilter) ([]models.Order, int, error)); ok {
		return rf(userID, page, limit, filter)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, models.OrderFilter) []models.Order); ok {
		r0 = rf(userID, page, limit, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int, models.OrderFilter) int); ok {
		r1 = rf(userID, page, limit, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int, models.OrderFilter) error); ok {
		r2 = rf(userID, page, limit, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderService_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockOrderService_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - userID uuid.UUID
//   - page int
//   - limit int
//   - filter models.OrderFilter
func (_e *MockOrderService_Expecter) GetAllByUserID(userID interface{}, page interface{}, limit interface{}, filter interface{}) *MockOrderService_GetAllByUserID_Call {
	return &MockOrderService_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", userID, page, limit, filter)}
}

func (_c *MockOrderService_GetAllByUserID_Call) Run(run func(userID uuid.UUID, page int, limit int, filter models.OrderFilter)) *MockOrderService_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int), args[3].(models.OrderFilter))
	})
	return _c
}

func (_c *MockOrderService_GetAllByUserID_Call) Return(_a0 []models.Order, _a1 int, _a2 error) *MockOrderService_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOrderService_GetAllByUserID_Call) RunAndReturn(run func(uuid.UUID, int, int, models.OrderFilter) ([]models.Order, int, error)) *MockOrderService_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: orderID
func (_m *MockOrderService) GetByID(orderID uuid.UUID) (models.Order, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (models.Order, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) models.Order); ok {
		r0 = rf(orderID)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - orderID uuid.UUID
func (_e *MockOrderService_Expecter) GetByID(orderID interface{}) *MockOrderService_GetByID_Call {
	return &MockOrderService_GetByID_Call{Call: _e.mock.On("GetByID", orderID)}
}

func (_c *MockOrderService_GetByID_Call) Run(run func(orderID uuid.UUID)) *MockOrderService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderService_GetByID_Call) Return(_a0 models.Order, _a1 error) *MockOrderService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_GetByID_Call) RunAndReturn(run func(uuid.UUID) (models.Order, error)) *MockOrderService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: orderID, userID, newStatus
func (_m *MockOrderService) UpdateStatus(orderID uuid.UUID, userID uuid.UUID, newStatus models.OrderStatus) (models.Order, error) {
	ret := _m.Called(orderID, userID, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, models.OrderStatus) (models.Order, error)); ok {
		return rf(orderID, userID, newStatus)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, models.OrderStatus) models.Order); ok {
		r0 = rf(orderID, userID, newStatus)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, models.OrderStatus) error); ok {
		r1 = rf(orderID, userID, newStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderService_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - orderID uuid.UUID
//   - userID uuid.UUID
//   - newStatus models.OrderStatus
func (_e *MockOrderService_Expecter) UpdateStatus(orderID interface{}, userID interface{}, newStatus interface{}) *MockOrderService_UpdateStatus_Call {
	return &MockOrderService_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", orderID, userID, newStatus)}
}

func (_c *MockOrderService_UpdateStatus_Call) Run(run func(orderID uuid.UUID, userID uuid.UUID, newStatus models.OrderStatus)) *MockOrderService_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID), args[2].(models.OrderStatus))
	})
	return _c
}

func (_c *MockOrderService_UpdateStatus_Call) Return(_a0 models.Order, _a1 error) *MockOrderService_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_UpdateStatus_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID, models.OrderStatus) (models.Order, error)) *MockOrderService_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
