// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "golang-order-manager-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: email, password
func (_m *MockAuthService) Login(email string, password string) (string, string, models.User, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 string
	var r2 models.User
	var r3 error
	if rf, ok := ret.Get(0).(func(string, string) (string, string, models.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string) models.User); ok {
		r2 = rf(email, password)
	} else {
		r2 = ret.Get(2).(models.User)
	}

	if rf, ok := ret.Get(3).(func(string, string) error); ok {
		r3 = rf(email, password)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) Login(email interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", email, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(email string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 string, _a1 string, _a2 models.User, _a3 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(string, string) (string, string, models.User, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: refreshToken
func (_m *MockAuthService) Logout(refreshToken string) error {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - refreshToken string
func (_e *MockAuthService_Expecter) Logout(refreshToken interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", refreshToken)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(refreshToken string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(_a0 error) *MockAuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function with given fields: userID
func (_m *MockAuthService) LogoutAll(userID uuid.UUID) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type MockAuthService_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockAuthService_Expecter) LogoutAll(userID interface{}) *MockAuthService_LogoutAll_Call {
	return &MockAuthService_LogoutAll_Call{Call: _e.mock.On("LogoutAll", userID)}
}

func (_c *MockAuthService_LogoutAll_Call) Run(run func(userID uuid.UUID)) *MockAuthService_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthService_LogoutAll_Call) Return(_a0 error) *MockAuthService_LogoutAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_LogoutAll_Call) RunAndReturn(run func(uuid.UUID) error) *MockAuthService_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: refreshToken
func (_m *MockAuthService) Refresh(refreshToken string) (string, string, models.User, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 string
	var r2 models.User
	var r3 error
	if rf, ok := ret.Get(0).(func(string) (string, string, models.User, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) models.User); ok {
		r2 = rf(refreshToken)
	} else {
		r2 = ret.Get(2).(models.User)
	}

	if rf, ok := ret.Get(3).(func(string) error); ok {
		r3 = rf(refreshToken)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - refreshToken string
func (_e *MockAuthService_Expecter) Refresh(refreshToken interface{}) *MockAuthService_Refresh_Call {
	return &MockAuthService_Refresh_Call{Call: _e.mock.On("Refresh", refreshToken)}
}

func (_c *MockAuthService_Refresh_Call) Run(run func(refreshToken string)) *MockAuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthService_Refresh_Call) Return(_a0 string, _a1 string, _a2 models.User, _a3 error) *MockAuthService_Refresh_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAuthService_Refresh_Call) RunAndReturn(run func(string) (string, string, models.User, error)) *MockAuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: username, email, password
func (_m *MockAuthService) Register(username string, email string, password string) (models.User, error) {
	ret := _m.Called(username, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (models.User, error)); ok {
		return rf(username, email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) models.User); ok {
		r0 = rf(username, email, password)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(username, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - username string
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) Register(username interface{}, email interface{}, password interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", username, email, password)}
}

func (_c *MockAuthService_Register_Call) Run(run func(username string, email string, password string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 models.User, _a1 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(string, string, string) (models.User, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
